name: Konversi Gambar ke Video

on:
  push:
    paths:
      - 'images/*.jpg' # Berjalan otomatis saat ada jpg baru di folder images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get install ffmpeg

      - name: Konversi Gambar ke Video
        run: |
          # Perintah ffmpeg untuk membuat video dari gambar
          ffmpeg -framerate 1 -i images/image%d.jpg -c:v libx264 -r 30 -pix_fmt yuv420p output.mp4

      - name: Unggah Hasil Video
        uses: actions/upload-artifact@v3
        with:
          name: video-hasil
          path: output.mp4
